### PR TITLE
Mac OS specific changes

### PR DESCRIPTION
**Pull request by cgarbe**
I have made some corrections necessary for running on Mac OS.

### CODE REVIEW

**Comment by hendriksiedelmann** [comment]
Looks mostly good, but please add "-std=c++11" to the CXX_FLAGS for clang and keep nested templates with >> (instead of > >).

If '''set(Boost_USE_STATIC_LIBS        ON)''' is required on MAC then don't set it globally (2f9b0ab
 /  gui/external/LFCamconfigurator/CMakeLists.txt)

**Comment by cgarbe** [comment]
Just one Problem: nested templates with ">>" result in an error with clang, hence my change to " > >"...

**Comment by hendriksiedelmann** [comment]
">>" nesting is supported since c++11, should work by adding "-std=c++11".

**Comment by cgarbe** [comment]
My mistake (I'm apparently still back in '98). Things changed back as you suggested and pushed to the master branch.

**Pull request merged**
